Full_App/Full_App/urls.py
from django.contrib import admin
from django.urls import path,include
from sign_up import views

app_name = 'sign_up'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),  # Assuming home is a view within the sign_up app
    path('sign_up/', include('sign_up.urls')),
    path('logout/',views.user_logout,name='logout'),
]

Full_App/sign_up/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'sign_up'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('',views.home,name='home'),
    path('login/',views.user_login,name='login'),
    path('logout/',views.user_logout, name='logout'),
]

Full_App/sign_up/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
    

Full_App/sign_up/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

Full_App/sign_up/views.py
from django.shortcuts import render
from .forms import UserForm,UserProfileForm
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
# Create your views here.
def home(request):
    return render(request,'sign_up/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user=user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm
        profile_form = UserProfileForm
    return render(request,'sign_up/registration.html',
                  {'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user=authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("account not active")
            
        else:
            print("someone tried to login but failed")
            print(f"username: {username},password: {password}")
            return HttpResponse("invalid login details supplied")
    else:
        return render(request,'sign_up/login.html')



    

Full_App/templates/sign_up/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title></title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'sign_up/base.css' %}" />
  </head>
  <body>
    <nav>
      <div>
        <ul>
          <li><a href="{%url 'sign_up:home'%}">Home</a></li>
          <li><a href="{%url 'sign_up:register'%}">Register</a></li>
          <li><a href="{%url 'admin:index'%}">Admin</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'sign_up:logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'sign_up:login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% block body_block %} {% endblock %}
  </body>
</html>

Full_App/templates/sign_up/index.html
{% extends 'sign_up/base.html' %} {% block body_block %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'sign_up/index.css' %}" />

    <title>Home Page</title>
  </head>
  <body>
    <div class="home-container">
      <h1>HEY, WELCOME TO THE HOME PAGE</h1>
      <p>
        Click <a href="{% url 'sign_up:register' %}">Register</a> to register
        your profile
      </p>
    </div>
  </body>
</html>
{% endblock %}

Full_App/templates/sign_up/login.html
{% extends 'sign_up/base.html' %} {% block body_block %}
<style>
  .wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
  }

  .login-container {
    max-width: 400px;
    width: 100%;
    padding: 20px;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    background-color: #f9f9f9;
  }
  .login-container h2 {
    text-align: center;
    margin-bottom: 20px;
  }
  .login-container form {
    display: flex;
    flex-direction: column;
  }
  .login-container label {
    margin-bottom: 5px;
    font-weight: bold;
  }
  .login-container input[type="text"],
  .login-container input[type="password"] {
    padding: 10px;
    margin-bottom: 20px;
    border: 1px solid #ccc;
    border-radius: 4px;
  }
  .login-container input[type="submit"] {
    padding: 10px;
    background-color: #007bff;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    font-size: 16px;
  }
  .login-container input[type="submit"]:hover {
    background-color: #0056b3;
  }
  .login-container .errors {
    color: red;
    margin-bottom: 10px;
  }
</style>

<div class="wrapper">
  <div class="login-container">
    <h2>Please Login!</h2>
    <form action="{% url 'sign_up:login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input
        type="text"
        name="username"
        placeholder="Enter your Username"
        required
      />

      <label for="password">Password:</label>
      <input
        type="password"
        name="password"
        placeholder="Enter your password"
        required
      />

      <input type="submit" value="Login" />
    </form>
    {% if form.errors %}
    <div class="errors">
      <ul>
        {% for field in form %} {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %} {% endfor %} {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

Full_App/templates/sign_up/registration.html
{% extends 'sign_up/base.html' %} {% block body_block %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'sign_up/registration.css' %}" />

    <title>Registration</title>
  </head>
  <body>

    <div class="registration-container">
      {% if registered %}
      <h1>THANK YOU FOR REGISTERING</h1>
      {% else %}
      <h1>Register Here</h1>
      <h3>Fill Out This Form:</h3>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %} {{ user_form.as_p }} {{ profile_form.as_p }}
        <input type="submit" value="Submit" class="submit-button" />
      </form>
 {% endif %}
    </div>
    {% endblock %}
  </body>
</html>